In [2]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [8]:
my_list=[0,1,2,3,4,5]
print(my_list)
print(type(my_list))

[0, 1, 2, 3, 4, 5]
<class 'list'>


In [9]:
arr=np.array(my_list)
print(arr)
print(type(arr))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


In [39]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [40]:
type(arr1)

numpy.ndarray

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [24]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [28]:
np.random.rand(4)

array([0.6755878 , 0.62039531, 0.37624956, 0.35557179])

In [29]:
np.random.rand(2,2)

array([[0.82757859, 0.20341187],
       [0.42730241, 0.4416417 ]])

In [37]:
np.random.randint(1,6)

4

In [6]:
np.random.randint(1,10,4)

array([3, 2, 2, 3], dtype=int32)

In [9]:
np.random.randint(1,10,10)

array([9, 5, 2, 9, 3, 9, 1, 3, 8, 7], dtype=int32)

In [15]:
ri=np.random.randint(10,40,(10,10))
ri

array([[22, 31, 37, 35, 12, 18, 36, 32, 32, 26],
       [17, 39, 32, 24, 20, 33, 32, 22, 22, 11],
       [29, 30, 34, 32, 10, 19, 24, 23, 17, 34],
       [24, 21, 17, 27, 27, 15, 36, 27, 35, 30],
       [31, 16, 12, 12, 21, 23, 13, 39, 16, 11],
       [24, 31, 29, 18, 16, 37, 37, 33, 18, 12],
       [30, 38, 27, 39, 25, 27, 31, 19, 14, 18],
       [38, 15, 26, 31, 11, 17, 24, 10, 21, 19],
       [27, 22, 30, 23, 38, 32, 21, 25, 20, 19],
       [31, 38, 12, 32, 29, 28, 33, 12, 32, 31]], dtype=int32)

In [16]:
ri=np.random.randint(10,40,(3,5))
ri

array([[22, 17, 29, 18, 20],
       [25, 31, 14, 26, 16],
       [22, 16, 25, 34, 24]], dtype=int32)

In [227]:
# Set seed for reproducibility
np.random.seed(0) 

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [17]:
len(ri)

3

In [18]:
ri.shape

(3, 5)

In [19]:
id(ri)

3129211091344

# Slicing in NumPy

In [20]:
ri[0:3]

array([[22, 17, 29, 18, 20],
       [25, 31, 14, 26, 16],
       [22, 16, 25, 34, 24]], dtype=int32)

In [24]:
r=np.random.randint(10,40,(10,10))
r

array([[15, 19, 34, 16, 38, 24, 29, 10, 34, 19],
       [27, 20, 18, 15, 15, 19, 27, 24, 36, 16],
       [24, 37, 18, 27, 37, 25, 38, 39, 38, 35],
       [10, 30, 25, 19, 36, 15, 31, 36, 29, 14],
       [14, 28, 13, 26, 35, 11, 32, 37, 17, 29],
       [36, 33, 32, 13, 37, 21, 35, 22, 30, 17],
       [35, 19, 25, 34, 14, 16, 28, 38, 33, 17],
       [37, 29, 36, 18, 23, 16, 28, 23, 21, 19],
       [27, 11, 37, 26, 28, 27, 14, 28, 26, 17],
       [19, 35, 19, 32, 32, 27, 24, 33, 32, 21]], dtype=int32)

In [22]:
r.shape

(10, 10)

In [23]:
print(r)

[[30 23 20 39 17 22 34 10 18 11]
 [33 39 27 31 31 15 17 27 21 38]
 [25 14 10 13 29 19 33 37 39 25]
 [33 15 31 18 23 23 27 33 10 30]
 [36 27 13 19 29 13 38 27 13 14]
 [15 14 38 13 29 22 12 33 13 33]
 [37 39 14 29 13 13 27 32 13 33]
 [12 18 33 10 33 10 16 18 27 10]
 [10 36 38 21 20 31 30 32 35 25]
 [24 17 36 26 21 37 31 10 19 12]]


In [24]:
r[:]

array([[30, 23, 20, 39, 17, 22, 34, 10, 18, 11],
       [33, 39, 27, 31, 31, 15, 17, 27, 21, 38],
       [25, 14, 10, 13, 29, 19, 33, 37, 39, 25],
       [33, 15, 31, 18, 23, 23, 27, 33, 10, 30],
       [36, 27, 13, 19, 29, 13, 38, 27, 13, 14],
       [15, 14, 38, 13, 29, 22, 12, 33, 13, 33],
       [37, 39, 14, 29, 13, 13, 27, 32, 13, 33],
       [12, 18, 33, 10, 33, 10, 16, 18, 27, 10],
       [10, 36, 38, 21, 20, 31, 30, 32, 35, 25],
       [24, 17, 36, 26, 21, 37, 31, 10, 19, 12]], dtype=int32)

In [25]:
r[3:8]

array([[33, 15, 31, 18, 23, 23, 27, 33, 10, 30],
       [36, 27, 13, 19, 29, 13, 38, 27, 13, 14],
       [15, 14, 38, 13, 29, 22, 12, 33, 13, 33],
       [37, 39, 14, 29, 13, 13, 27, 32, 13, 33],
       [12, 18, 33, 10, 33, 10, 16, 18, 27, 10]], dtype=int32)

In [27]:
print(r[3,8])

10


In [31]:
print(r[-5])

[15 14 38 13 29 22 12 33 13 33]


In [30]:
print(r[-5,-3])

33


In [32]:
r[::3]

array([[30, 23, 20, 39, 17, 22, 34, 10, 18, 11],
       [33, 15, 31, 18, 23, 23, 27, 33, 10, 30],
       [37, 39, 14, 29, 13, 13, 27, 32, 13, 33],
       [24, 17, 36, 26, 21, 37, 31, 10, 19, 12]], dtype=int32)

In [33]:
r[::-1]

array([[24, 17, 36, 26, 21, 37, 31, 10, 19, 12],
       [10, 36, 38, 21, 20, 31, 30, 32, 35, 25],
       [12, 18, 33, 10, 33, 10, 16, 18, 27, 10],
       [37, 39, 14, 29, 13, 13, 27, 32, 13, 33],
       [15, 14, 38, 13, 29, 22, 12, 33, 13, 33],
       [36, 27, 13, 19, 29, 13, 38, 27, 13, 14],
       [33, 15, 31, 18, 23, 23, 27, 33, 10, 30],
       [25, 14, 10, 13, 29, 19, 33, 37, 39, 25],
       [33, 39, 27, 31, 31, 15, 17, 27, 21, 38],
       [30, 23, 20, 39, 17, 22, 34, 10, 18, 11]], dtype=int32)

In [35]:
r

array([[30, 23, 20, 39, 17, 22, 34, 10, 18, 11],
       [33, 39, 27, 31, 31, 15, 17, 27, 21, 38],
       [25, 14, 10, 13, 29, 19, 33, 37, 39, 25],
       [33, 15, 31, 18, 23, 23, 27, 33, 10, 30],
       [36, 27, 13, 19, 29, 13, 38, 27, 13, 14],
       [15, 14, 38, 13, 29, 22, 12, 33, 13, 33],
       [37, 39, 14, 29, 13, 13, 27, 32, 13, 33],
       [12, 18, 33, 10, 33, 10, 16, 18, 27, 10],
       [10, 36, 38, 21, 20, 31, 30, 32, 35, 25],
       [24, 17, 36, 26, 21, 37, 31, 10, 19, 12]], dtype=int32)

In [34]:
r[::-5]

array([[24, 17, 36, 26, 21, 37, 31, 10, 19, 12],
       [36, 27, 13, 19, 29, 13, 38, 27, 13, 14]], dtype=int32)

In [36]:
r[2]

array([25, 14, 10, 13, 29, 19, 33, 37, 39, 25], dtype=int32)

In [40]:
print(r[2])
print(r[:, 2])

[25 14 10 13 29 19 33 37 39 25]
[20 27 10 31 13 38 14 33 38 36]


In [41]:
print(r[:,-7])

[39 31 13 18 19 13 29 10 21 26]


In [42]:
print(r[0:3, 0:3])

[[30 23 20]
 [33 39 27]
 [25 14 10]]


In [25]:
r

array([[15, 19, 34, 16, 38, 24, 29, 10, 34, 19],
       [27, 20, 18, 15, 15, 19, 27, 24, 36, 16],
       [24, 37, 18, 27, 37, 25, 38, 39, 38, 35],
       [10, 30, 25, 19, 36, 15, 31, 36, 29, 14],
       [14, 28, 13, 26, 35, 11, 32, 37, 17, 29],
       [36, 33, 32, 13, 37, 21, 35, 22, 30, 17],
       [35, 19, 25, 34, 14, 16, 28, 38, 33, 17],
       [37, 29, 36, 18, 23, 16, 28, 23, 21, 19],
       [27, 11, 37, 26, 28, 27, 14, 28, 26, 17],
       [19, 35, 19, 32, 32, 27, 24, 33, 32, 21]], dtype=int32)

In [44]:
print(r[2:4, 4:6])

[[29 19]
 [23 23]]


In [2]:
a1=np.array([10,20,30,40])
a1

array([10, 20, 30, 40])

In [4]:
a1.min()

np.int64(10)

In [5]:
a1.max()

np.int64(40)

In [6]:
a1.mean()

np.float64(25.0)

In [8]:
from numpy import *
median(a1)

np.float64(25.0)

In [9]:
a1

array([10, 20, 30, 40])

In [10]:
a1.reshape(2,2)

array([[10, 20],
       [30, 40]])

In [11]:
a1.reshape(4,1)

array([[10],
       [20],
       [30],
       [40]])

In [12]:
a1.reshape(1,4)

array([[10, 20, 30, 40]])

In [19]:
a1.reshape(2,2)

array([[10, 20],
       [30, 40]])

In [21]:
a1.reshape(2,2, order='F')

array([[10, 30],
       [20, 40]])

In [48]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
np.arange(1,21).reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [63]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Indexing

In [26]:
r

array([[15, 19, 34, 16, 38, 24, 29, 10, 34, 19],
       [27, 20, 18, 15, 15, 19, 27, 24, 36, 16],
       [24, 37, 18, 27, 37, 25, 38, 39, 38, 35],
       [10, 30, 25, 19, 36, 15, 31, 36, 29, 14],
       [14, 28, 13, 26, 35, 11, 32, 37, 17, 29],
       [36, 33, 32, 13, 37, 21, 35, 22, 30, 17],
       [35, 19, 25, 34, 14, 16, 28, 38, 33, 17],
       [37, 29, 36, 18, 23, 16, 28, 23, 21, 19],
       [27, 11, 37, 26, 28, 27, 14, 28, 26, 17],
       [19, 35, 19, 32, 32, 27, 24, 33, 32, 21]], dtype=int32)

In [27]:
row,col=4,5

In [29]:
print(r[row,col])

11


# NumPy Masking or Filter

In [30]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
id(mat)

3129215144688

In [67]:
mat.shape

(10, 10)

In [69]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [70]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [73]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
# Create a boolean mask for values greater than 25
mask = arr > 25
print(mask)
print(arr[arr>25])

[False False  True  True  True]
[30 40 50]


In [31]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [34]:
print(mat[mat==50])

[50]


In [33]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [37]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# Python Program to generate OTP

In [43]:
import random as r
def generate_otp(length=4):
    digits='012345'
    otp=''.join(r.choice(digits) for _ in range(length))
    return otp
otp_length=4
otp=generate_otp(otp_length)
print(otp)

0400


In [48]:
z1 = np.arange(12).reshape(3,4) 
z2 = np.arange(12,24).reshape(3,4)
print(z1)
print()
print()
print(z2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [49]:
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [50]:
z2-2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [51]:
z1*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [54]:
z2//2

array([[ 6,  6,  7,  7],
       [ 8,  8,  9,  9],
       [10, 10, 11, 11]])

In [55]:
z1%4

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [58]:
z1<5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [63]:
z2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
z1+z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [68]:
z2-z1

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [69]:
z1*z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [73]:
z2//z1

C:\Users\tkaly\AppData\Local\Temp\ipykernel_41516\2489448343.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  z2//z1


array([[ 0, 13,  7,  5],
       [ 4,  3,  3,  2],
       [ 2,  2,  2,  2]])

In [79]:
print(z1.mean())

5.5


In [80]:
print(z2.mean())

17.5


In [81]:
print(median(z1))

5.5


In [82]:
print(median(z2))

17.5


In [84]:
print(z1.std())

3.452052529534663


In [87]:
print(z2.std(axis=0))

[3.26598632 3.26598632 3.26598632 3.26598632]


In [88]:
print(sin(z1))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]


In [89]:
print(cos(z2))

[[ 0.84385396  0.90744678  0.13673722 -0.75968791]
 [-0.95765948 -0.27516334  0.66031671  0.98870462]
 [ 0.40808206 -0.54772926 -0.99996083 -0.53283302]]


In [90]:
print(tan(z1))

[[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01]
 [ 1.15782128e+00 -3.38051501e+00 -2.91006191e-01  8.71447983e-01]
 [-6.79971146e+00 -4.52315659e-01  6.48360827e-01 -2.25950846e+02]]


In [92]:
s2 = np.arange(12).reshape(3,4) 
s3 = np.arange(12,24).reshape(4,3)

In [93]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [95]:
print(dot(s2,s3))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [96]:
print(exp(s2)) # Lag and exponents

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


# Round, Floor, Ceil

In [97]:
arr2 = np.array([1.2, 2.7, 3.5, 4.9]) 
rounded_arr = np.round(arr2) 
print(rounded_arr) 

[1. 3. 4. 5.]


In [98]:
arr2 = np.array([1.234, 2.567, 3.891]) 
rounded_arr = np.round(arr2, decimals=2) 
print(rounded_arr) 

[1.23 2.57 3.89]


In [99]:
np.round(np.random.random((2,3))*100) 

array([[69., 53., 96.],
       [75., 99., 62.]])

In [100]:
arr = np.array([1.2, 2.7, 3.5, 4.9]) 
floored_arr = np.floor(arr) 
print(floored_arr) 

[1. 2. 3. 4.]


In [101]:
np.floor(np.random.random((2,3))*100) 

array([[24., 16., 59.],
       [21., 96., 68.]])

In [103]:
arr=np.array([1.2,2.7,3.8,4.9])
ceil_arr=np.ceil(arr)
print(ceil_arr)

[2. 3. 4. 5.]


In [104]:
np.ceil(np.random.random((2,3))*100) 

array([[23., 18., 20.],
       [97., 33.,  7.]])

In [116]:
x=np.array([3,2.2,4.6])
x

array([3. , 2.2, 4.6])

In [117]:
print(np.round(x))

[3. 2. 5.]


In [142]:
z1=np.array([[0,1,2,3],
             [4,5,6,7],
             [8,9,10,11]])
print(z1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [141]:
print(np.max(z1))
print(np.min(z1))
print(np.sum(z1))
z2=np.array([[12,13,14],
             [15,16,17],
             [18,19,20],
             [21,22,23]])
print(np.prod(z2))

11
0
66
647647525324800


In [131]:
print(np.mean(z1))
print(np.median(z1))
print(np.std(z1))
print(np.var(z1))

5.5
5.5
3.452052529534663
11.916666666666666


In [133]:
print(np.sin(z1))
print()
print(np.cos(z1))
print()
print(np.tan(z1))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]

[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257 ]]

[[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01]
 [ 1.15782128e+00 -3.38051501e+00 -2.91006191e-01  8.71447983e-01]
 [-6.79971146e+00 -4.52315659e-01  6.48360827e-01 -2.25950846e+02]]


In [136]:
print(np.cot(z1))

AttributeError: module 'numpy' has no attribute 'cot'

In [143]:
print(np.dot(z1,z2))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [144]:
w1 = np.arange(12).reshape(3,4) 
w2 = np.arange(12,24).reshape(3,4)
print(w1)
print()
print(w2)
print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [147]:
print(np.hsplit(w1,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [148]:
import numpy as np
# Define the sigmoid function
def sigmoid(x):
   return 1 / (1 + np.exp(-x))
# Test the function
input_values = np.array([-10, -1, 0, 1, 10])
output_values = sigmoid(input_values)
print("Sigmoid Output:", output_values)

Sigmoid Output: [4.53978687e-05 2.68941421e-01 5.00000000e-01 7.31058579e-01
 9.99954602e-01]


In [153]:
actual = np.random.randint(1,20,5) 
predicted = np.random.randint(1,20,5) 

In [154]:
actual

array([15,  3,  1, 12,  4], dtype=int32)

In [155]:
predicted

array([ 9,  7, 13,  6,  4], dtype=int32)

In [157]:
def mse(actual,predicted):
    return np.mean((actual-predicted)**2) 
print(mse(actual,predicted)) 

46.4


In [158]:
 p1 = np.arange(10) 
 p2 = np.arange(12).reshape(3,4) 
 p3 = np.arange(8).reshape(2,2,2)

In [160]:
print(p1,'\n\n',p2,'\n\n',p3)

[0 1 2 3 4 5 6 7 8 9] 

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [162]:
#Indexing on 1D Array
print(p1[-1])

9


In [163]:
print(p1[0])

np.int64(0)

In [164]:
# Indexing on 2D Array
print(p2[2,3])

11


In [166]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [165]:
#Indexing on 3D Array
print(p3[1,0,1])

5


In [170]:
print(p3[0,1,0])

2


# Slicing

In [171]:
#slicing on 1D
p1[2:5] 

array([2, 3, 4])

In [172]:
p1[2:5:2]

array([2, 4])

In [174]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
# Slicing on 2D
p2[0,:]

array([0, 1, 2, 3])

In [175]:
p2[:,2] 

array([ 2,  6, 10])

In [176]:
p2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [177]:
p2[::2, ::3] 

array([[ 0,  3],
       [ 8, 11]])

In [178]:
p3 = np.arange(27).reshape(3,3,3) 
p3 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [179]:
p3[1] 

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [180]:
p3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [181]:
p3[0::2 , 0]

array([[ 0,  1,  2],
       [18, 19, 20]])

In [183]:
p3[0::2 , 0 , ::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [184]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [186]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [187]:
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [188]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [189]:
for i in p3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [190]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [191]:
# Transpose
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [192]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [196]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [195]:
p3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [197]:
# Ravel
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [198]:
p3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [199]:

w1 = np.arange(12).reshape(3,4) 
w2 = np.arange(12,24).reshape(3,4) 

In [200]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [201]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [202]:
#Hstack-Horizantal stacking
hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [204]:
#Vstack- Vertical Stacing
vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [205]:
hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [206]:
vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

# Speed of List vs NumPy

In [207]:
# List
a = [ i for i in range(10000000)] 
b = [i for i in range(10000000,20000000)] 
c = [] 
import time 
start = time.time() 
for i in range(len(a)): 
    c.append(a[i] + b[i]) 
print(time.time()-start)

4.79682469367981


In [208]:
# NumPy
import numpy as np 
a = np.arange(10000000) 
b = np.arange(10000000,20000000) 
start =time.time() 
c = a+b 
print(time.time()-start) 

0.3597829341888428


# Memory Used for List Vs Numpy

In [209]:
P= [i for i in range(10000000)] 
 
import sys 
 
sys.getsizeof(P)

89095160

In [210]:
R= np.arange(10000000) 
 
sys.getsizeof(R) 

80000112

# Fancy Indexing

In [213]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [214]:
w1[[0]]

array([[0, 1, 2, 3]])

In [215]:
z = np.arange(24).reshape(6,4) 

In [216]:
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [217]:
z[[0,2,3,5]] 

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [218]:
 
z[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [220]:
# Same Shape
a = np.arange(6).reshape(2,3) 
b = np.arange(6,12).reshape(2,3) 
 
print(a,'\n\n') 
print(b,'\n\n') 
 
print(a+b)

[[0 1 2]
 [3 4 5]] 


[[ 6  7  8]
 [ 9 10 11]] 


[[ 6  8 10]
 [12 14 16]]


In [222]:
#Different Shape
a = np.arange(6).reshape(2,3) 
b = np.arange(3).reshape(1,3)
 
print(a,'\n\n') 
print(b,'\n\n') 
 
print(a+b)

[[0 1 2]
 [3 4 5]] 


[[0 1 2]] 


[[0 2 4]
 [3 5 7]]


# Working with Missing Values

In [223]:

S = np.array([1,2,3,4,np.nan,6]) 
S 

array([ 1.,  2.,  3.,  4., nan,  6.])

In [224]:
np.isnan(S)

array([False, False, False, False,  True, False])

In [225]:
S[np.isnan(S)] # Nan values

array([nan])

In [226]:
S[~np.isnan(S)] # Not Nan Values


array([1., 2., 3., 4., 6.])

# Set Operations

In [228]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [229]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# Array Attribute Functions

In [230]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64
