# Adavanced NumPy

# Array Creation

In [1]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4])

In [5]:
print('Array: 'arr1)

[1 2 3 4]


In [23]:
arr2=np.arange(1,20,4)
print('Creating Array Using arange()->  ',arr2)

Creating Array Using arange()->   [ 1  5  9 13 17]


In [27]:
arr3=np.zeros((2,3),dtype=int)
print('Creating Array using only Zeros: \n',arr3)

Creating Array using only Zeros: 
 [[0 0 0]
 [0 0 0]]


In [28]:
arr4=np.ones((2,2),dtype=int)
print('Creating Array using only Ones: \n',arr4)

Creating Array using only Ones: 
 [[1 1]
 [1 1]]


In [30]:
arr5=np.eye(3,dtype=int)
print('Creatig Identity Array Using eye(): \n',arr5)

Creatig Identity Array Using eye(): 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
arr6=np.identity(4)
print('Creatig Identity Array Using identity(): \n',arr6)

Creatig Identity Array Using identity(): 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulation Funtions

In [40]:
a1=np.array([[1,2,3],[4,5,6]])
print('Actual Array: \n',a1) 
reshaped=np.reshape(a1,(3,2))
print()
print('Reshaped Array: \n',reshaped)

Actual Array: 
 [[1 2 3]
 [4 5 6]]

Reshaped Array: 
 [[1 2]
 [3 4]
 [5 6]]


In [43]:
# Flattened Array
flatten=np.ravel(reshaped)
print('Flattend Array: \n', flatten)

Flattend Array: 
 [1 2 3 4 5 6]


In [46]:
# Transpose an Array
a2=np.array([[1,2],[3,4],[5,6]])
print('Array: \n', a2)
tr=np.transpose(a2)
print()
print('Transposed Array: \n', tr)

Array: 
 [[1 2]
 [3 4]
 [5 6]]

Transposed Array: 
 [[1 3 5]
 [2 4 6]]


In [52]:
#Stack Array Vertically
a3=np.array([1,2,3])
a4=np.array([4,5,6])
a5=np.array([7,8,9])
vstack=np.vstack([a3,a4,a5])
print('Vertical Stack Array: \n', vstack)

Vertical Stack Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
#Stack Array Horizantally
a3=np.array([1,2,3])
a4=np.array([4,5,6])
a5=np.array([7,8,9])
hstack=np.hstack([a3,a4,a5])
print('Horizantal Stack Array: \n', hstack)

Horizantal Stack Array: 
 [1 2 3 4 5 6 7 8 9]


# Mathematical Functions

In [58]:
#adding
print('Array:',a3)
added=np.add(a3,5)
print()
print('Add function in math for NumPy: \n', added)

Array: [1 2 3]

Add function in math of NumPy: 
 [6 7 8]


In [59]:
#Squarring
square=np.power(a3,3)
print('Power function in math for NumPy: \n', square)

Power function in math for NumPy: 
 [ 1  8 27]


In [61]:
#square root of each value 
s_root=np.sqrt(a3)
print('Square root of each value in Array:', s_root)

Square root of each value in Array: [1.         1.41421356 1.73205081]


In [70]:
print('Actual Arrays:\n', 'Array 1\n', a3, '\n\nArray 2\n', a4)
#Dot Product of 2 arrays
dot_arr=np.dot(a3,a4)
print('\nDot Product of 2 Arrays:\n ', dot_arr)

Actual Arrays:
 Array 1
 [1 2 3] 

Array 2
 [4 5 6]

Dot Product of 2 Arrays:
  32


In [71]:
# Cross Product
cross_arr=np.cross(a3,a4)
print('\nCross Product of 2 Arrays:\n ', cross_arr)


Cross Product of 2 Arrays:
  [-3  6 -3]


# Statistaical Functions

In [72]:
a6=np.array([10,20,30,40,50])
a6

array([10, 20, 30, 40, 50])

In [73]:
# mean of an array
np.mean(a6)

np.float64(30.0)

In [74]:
# variance of an array
np.var(a6)

np.float64(200.0)

In [75]:
# Standard Deviation of an Array
np.std(a6)

np.float64(14.142135623730951)

In [76]:
# Mininum of element of an array
np.min(a6)

np.int64(10)

In [77]:
#Maximum Element
np.max(a6)

np.int64(50)

In [78]:
# Sum of an array
np.sum(a6)

np.int64(150)

# Random Sampling Functions

In [80]:
rand_val=np.random.rand(3)
rand_val

array([0.71707923, 0.80276283, 0.80661722])

In [99]:
rand_val1=np.random.randint(1,5,3)
rand_val1

array([3, 3, 4], dtype=int32)

In [101]:
#Set Seed for reproductivity
np.random.seed(4)
rand_val2=np.random.randint(1,10,4)
rand_val2

array([8, 6, 2, 9], dtype=int32)

# Boolean and Logical Functions

In [104]:
# all() Function
arr = np.array([True, True, False])
all_true = np.all(arr)
print(all_true)

False


In [105]:
# all() Function
arr = np.array([True, True])
all_true = np.all(arr)
print(all_true)

True


In [106]:
# all() Function
arr = np.array([True, False])
all_true = np.all(arr)
print(all_true)

False


In [107]:
# any() Function
arr = np.array([True, False])
any_true = np.any(arr)
print(all_true)

True


In [108]:
# all() Function
arr = np.array([False, False])
all_true = np.all(arr)
print(all_true)

False


In [110]:
# any() Function
arr = np.array([False, False])
any_true = np.any(arr)
print(all_true)

False


# SET Operations

In [114]:
set1=np.array([1,2,3,4,5])
set2=np.array([4,5,6,7,8])
print('2 Sets:', '\nSET 1:',set1, '\nSET 2:',set2)

2 Sets: 
SET 1: [1 2 3 4 5] 
SET 2: [4 5 6 7 8]


In [115]:
np.intersect1d(set1,set2)

array([4, 5])

In [116]:
np.union1d(set1,set2)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
np.unique_counts((set1,set2))

UniqueCountsResult(values=array([1, 2, 3, 4, 5, 6, 7, 8]), counts=array([1, 1, 1, 2, 2, 1, 1, 1]))

In [121]:
np.unique_all((set1,set2))

UniqueAllResult(values=array([1, 2, 3, 4, 5, 6, 7, 8]), indices=array([0, 1, 2, 3, 4, 7, 8, 9]), inverse_indices=array([[0, 1, 2, 3, 4],
       [3, 4, 5, 6, 7]]), counts=array([1, 1, 1, 2, 2, 1, 1, 1]))

In [122]:
np.unique_inverse((set1,set2))

UniqueInverseResult(values=array([1, 2, 3, 4, 5, 6, 7, 8]), inverse_indices=array([[0, 1, 2, 3, 4],
       [3, 4, 5, 6, 7]]))

In [126]:
arr = np.array([1, 2, 3, 4, 5])
shape = arr.shape
size = arr.size
dimensions = arr.ndim # Number of dimensions
dtype = arr.dtype # Data type of the array elements
print("Shape of a: ", shape)
print("Size of a: ", size)
print("Number of dimensions of a: ", dimensions)
print("Data type of a: ", dtype)
type_change=np.astype(arr,float)
print('Changing Data Type: ',type_change)

Shape of a:  (5,)
Size of a:  5
Number of dimensions of a:  1
Data type of a:  int64
Changing Data Type:  [1. 2. 3. 4. 5.]


# Other Functions

In [127]:
a3

array([1, 2, 3])

In [129]:
copy_a3=np.copy(a3)
copy_a3

array([1, 2, 3])

In [130]:
id(a3)

2632650247696

In [131]:
id(copy_a3)

2632647891664

In [132]:
array_size_bytes = a3.nbytes
print("Size of a in bytes: \n", array_size_bytes)

Size of a in bytes: 
 24


In [134]:
np.amin(a3)

np.int64(1)

In [135]:
np.amax(a3)

np.int64(3)

# Trignometry Functions

In [145]:
trigno=np.array([0,1,3])

In [146]:
np.arccos(trigno)

C:\Users\tkaly\AppData\Local\Temp\ipykernel_15848\4283579485.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(trigno)


array([1.57079633, 0.        ,        nan])

In [147]:
np.arcsin(trigno)

C:\Users\tkaly\AppData\Local\Temp\ipykernel_15848\2584180276.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(trigno)


array([0.        , 1.57079633,        nan])

In [148]:
np.arccosh(trigno)

C:\Users\tkaly\AppData\Local\Temp\ipykernel_15848\2112338386.py:1: RuntimeWarning: invalid value encountered in arccosh
  np.arccosh(trigno)


array([       nan, 0.        , 1.76274717])

In [149]:
np.arcsinh(trigno)

array([0.        , 0.88137359, 1.81844646])

In [150]:
np.arctan(trigno)

array([0.        , 0.78539816, 1.24904577])

In [151]:
np.arctanh(trigno)

C:\Users\tkaly\AppData\Local\Temp\ipykernel_15848\1566213536.py:1: RuntimeWarning: divide by zero encountered in arctanh
  np.arctanh(trigno)
C:\Users\tkaly\AppData\Local\Temp\ipykernel_15848\1566213536.py:1: RuntimeWarning: invalid value encountered in arctanh
  np.arctanh(trigno)


array([ 0., inf, nan])

In [153]:
np.arctan2(a3,a4)

array([0.24497866, 0.38050638, 0.46364761])